name: An25

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Esto ejecuta la acción cada hora; puedes ajustarlo según tus necesidades.

jobs:
  update-document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages("rmarkdown")'

      - name: Render R Markdown document
        run: |
          Rscript -e 'rmarkdown::render("ruta/a/tu/documento.Rmd")'

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update rendered document"
          git push

